---
title: '[번역] #11: 리액트 쿼리의 에러 핸들링'
date: 2022-05-19 20:17:02
category: react
thumbnail: './images/react.png'
draft: false
---


<div>

<img src="./images/2022-react-00.png">

</div>

> Thanks for [@TkDodo](https://github.com/tkdodo)
>> 해당 컨텐츠는 [원글](https://tkdodo.eu/blog/react-query-error-handling)을 번역한 것입니다. 오타, 오역 지적은 환영이에요!

<br>

# #11: React Query Error Handling

오류 처리 작업은 비동기 데이터, 특히 data fetching에 필수적인 부분입니다. 우리는 이걸 직시해야 하는데, 모든 요청이 성공하는 것은 아니며 모든 Promise가 이행되는 것도 아닙니다.

종종 우리가 처음부터 제대로 집중하지 않는 다고 생각했습니다. 우리는 오류 처리 시 "햇볕 사례"를 먼저 처리하는 것을 좋아하니까요.

그러나 오류 처리에 대한 방법을 고민하지 않는 건 사용자 경험에 부정적인 영향을 미칠 수 있습니다. 이러한 문제를 방지하기 위해 React Query가 제공하는 오류 처리와 관련된 옵션을 자세히 살펴보겠습니다.

## **Prerequisites**

오류를 올바르게 처리하려면 React Query에서 거부(rejected)된 Promise가 필요합니다. 운 좋게도, 이것은 여러분이 [axios](https://axios-http.com/)와 같은 라이브러리를 다룰 때 얻을 수 있죠.

만약 당신이 [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) 또는 4xx나 5xx와 같은 잘못된 상태 코드에 대해 거부된 Promise를 제공하지 않는 다른 라이브러리를 사용하고 있다면, 당신은 직접 *queryFn*을 통해 변환해야 합니다. 이 내용은 공식 문서에서 다루고 있어요.

## **The standard example**

오류 표시와 관련된 대부분의 예를 살펴볼게요.

```tsx
function TodoList() {
  const todos = useQuery(['todos'], fetchTodos)

  if (todos.isLoading) {
    return 'Loading...'
  }

  // ✅ standard error handling
  // could also check for: todos.status === 'error'
  if (todos.isError) {
    return 'An error occurred'
  }

  return (
    <div>
      {todos.data.map((todo) => (
        <Todo key={todo.id} {...todo} />
      ))}
    </div>
  )
}
```

여기서는 React Query에서 제공한 *isError* boolean 플래그(*status* enum에서 파생됨)를 확인하여 오류 상황을 처리하고 있습니다.

일부 시나리오에서는 이 방법이 문제가 되진 않지만, 분명 단점도 있습니다.

1. 백그라운드 오류를 잘 처리하지 못합니다. 백그라운드 refetch가 실패했다고 해서 전체 Todo List를 언마운트해야 할까요? api가 일시적으로 다운되었거나 속도 제한에 도달했을 수 있지만 몇 분 후 다시 동작할 수 있습니다. 이러한 상황을 개선하는 방법을 알아보려면 React Query의 [#4: Status Checks in React Query](https://tkdodo.eu/blog/status-checks-in-react-query)
을 참조해 주세요.
2. 쿼리를 사용하고자 하는 모든 컴포넌트에서 보일러 플레이트를 적용해야만 상당히 쉬워집니다.

두 번째 문제를 해결하기 위해 React 자체적으로 제공하는 훌륭한 기능을 사용할 수 있습니다.

## **Error Boundaries**

[오류 경계(Error Boundaries)](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries)는 렌더링 중에 발생하는 런타임 오류를 포착하기 위한 리액트의 개념으로, 이를 통해 적절하게 반응하여 폴백 UI로 표시할 수 있습니다.

컴포넌트를 원하는 세분화로 오류 경계를 래핑할 수 있으므로 나머지 UI는 해당 오류의 영향을 받지 않습니다.

오류 경계는 렌더링 중에 발생하지 않기 때문에 비동기 오류를 포착할 수 없습니다. 오류 경계가 React Query에서 동작하기 위해 내부적으로 오류를 잡아 다음 렌더링 주기에 다시 던져(throw) 오류 경계가 오류를 선택할 수 있도록 합니다.

이것은 매우 천재적이면서도 간단한 오류 처리 방식이며, 이 작업을 수행하기 위해 필요한 것은 *useErrorBoundary* 플래그를 쿼리에 전달(또는 기본 구성을 통해 제공)하는 것입니다.

```tsx
function TodoList() {
  // ✅ will propagate all fetching errors to the nearest Error Boundary
  const todos = useQuery(['todos'], fetchTodos, { useErrorBoundary: true })

  if (todos.data) {
    return (
      <div>
        {todos.data.map((todo) => (
          <Todo key={todo.id} {...todo} />
        ))}
      </div>
    )
  }

  return 'Loading...'
}
```

[v3.23.0](https://github.com/tannerlinsley/react-query/releases/tag/v3.23.0)부터는 *useErrorBoundary*라는 함수를 제공하여 오류 경계로 이동할 오류와 지역적으로 처리할 오류를 지정할 수도 있습니다.

```tsx
useQuery(['todos'], fetchTodos, {
  // 🚀 only server errors will go to the Error Boundary
  useErrorBoundary: (error) => error.response?.status >= 500,
})
```

이것은 [mutations](https://react-query.tanstack.com/guides/mutations)에도 효과가 있으며, form을 제출 할 때 매우 유용합니다. 4xx 범위의 오류는 지역적으로 처리할 수 있는 반면(예: 백엔드 유효성 검사에 실패한 경우), 모든 5xx 서버 오류는 오류 경계로 전파될 수 있습니다.

## **Showing error notifications**

일부 use-case의 경우 화면에 경고 배너를 렌더링하는 대신, 나타난 뒤 자동으로 사라지는 오류 토스트(toast) 알림을 표시하는 것이 더 나을 수 있습니다. 이것들은 보통 [react-hot-toast](https://react-hot-toast.com/)에서 제공하는 명령형 api로 사용할 수 있습니다.

```tsx
import toast from 'react-hot-toast'

toast.error('Something went wrong')
```

그러면 React Query에서 오류가 발생할 때 어떻게 이 작업을 수행할 수 있을까요?

## **The onError callback**

```tsx
const useTodos = () =>
  useQuery(['todos'], fetchTodos, {
    // ⚠️ looks good, but is maybe _not_ what you want
    onError: (error) =>
      toast.error(`Something went wrong: ${error.message}`),
  })
```

언뜻 보기에는, *onError* 콜백이 정확히 fetch에 실패한 때 부작용을 수행하는 데 필요한 것처럼 보입니다. 또한 우리가 Custom Hook을 한 번만 사용하는 한, 효과가 있을 거에요!

모든 *Observer*에 대해 *useQuery* 사용 시 *onError* 콜백이 호출됩니다. 즉, 애플리케이션에서 *useTodos*를 두 번 호출하면 네트워크 요청이 하나만 실패하더라도 두 번의 오류 토스트가 발생합니다.

개념적으로 onError 콜백이 *useEffect*와 유사하게 기능한다 생각할 수 있죠.. 위의 예제를 해당 구문으로 확장하면 모든 사용자에 대해 실행된다는 것이 더욱 분명해질 것입니다.

```tsx
const useTodos = () => {
  const todos = useQuery(['todos'], fetchTodos)

  // 🚨 effects are executed for every component
  // that uses this custom hook individually
  React.useEffect(() => {
    if (todos.error) {
      toast.error(`Something went wrong: ${todos.error.message}`)
    }
  }, [todos.error])

  return todos
}
```

물론, 콜백을 Custom Hook에 추가하지 않고 Hook을 호출할 경우에도 괜찮습니다. 그러나 모든 Observer에게 fetch가 실패했음을 통지하지 않고 기본적인 fetch가 실패했음을 사용자에게 통지하려면 어떻게 해야 할까요? 이를 위해 React Query에는 다른 콜백이 있습니다.

## **The global callbacks**

전역 콜백은 쿼리 캐시를 만들 때 제공되어야 하고, 새 쿼리 클라이언트를 만들 때 암묵적으로 발생하지만 다음을 사용자가 정의할 수도 있습니다.

```tsx
const queryClient = new QueryClient({
  queryCache: new QueryCache({
    onError: (error) =>
      toast.error(`Something went wrong: ${error.message}`),
  }),
})
```

이제 각 쿼리에 대해 한 번만 오류 토스트가 표시되며, 이것이 정확히 원하는 것입니다🥳  또한 기본 옵션과 같이 한 번만 실행되도록 보장되고 덮어쓸 수 없기 때문에 수행하려는 모든 종류의 오류 추적 또는 모니터링을 배치하는 데 최적의 장소일 수 있습니다.

## **Putting it all together**

React Query에서 오류를 처리하는 세 가지 주요 방법은 다음과 같습니다.

- useQuery에서 반환된 오류 속성
- *onError* 콜백(쿼리 자체 또는 글로벌 QueryCache/MutionCache)
- 오류 경계 사용

원하는 대로 혼합하고 일치시킬 수 있습니다. 제가 개인적으로 하고 싶은 일은 백그라운드 재검색(오래된 UI를 그대로 유지하기 위해)에 대한 오류 토스트를 표시하고 다른 모든 작업을 로컬 또는 Error Boundaries로 처리하는 것입니다.

```tsx
const queryClient = new QueryClient({
  queryCache: new QueryCache({
    onError: (error, query) => {
      // 🎉 only show error toasts if we already have data in the cache
      // which indicates a failed background update
      if (query.state.data !== undefined) {
        toast.error(`Something went wrong: ${error.message}`)
      }
    },
  }),
})
```